-- CREATED BY VERTABELO (HTTP://VERTABELO.COM)
-- LAST MODIFICATION DATE: 2024-04-04 21:51:17.94

-- TABLES
-- TABLE: ADDRESSES
CREATE TABLE ADDRESSES (
    ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    INFO VARCHAR(250)  NOT NULL,
    CITY VARCHAR(150)  NOT NULL,
    REGION VARCHAR(150)  NOT NULL,
    POSTAL_CODE VARCHAR(20)  NOT NULL,
    COUNTRY VARCHAR(100)  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT ADDRESSES_PK PRIMARY KEY (ID)
);

-- TABLE: CATEGORIES
CREATE TABLE CATEGORIES (
    ID INT  NOT NULL,
    NAME VARCHAR(100)  NOT NULL,
    DESCRIPTION TEXT  NOT NULL,
    PICTURE BYTEA  NOT NULL,
    CONSTRAINT CATEGORIES_PK PRIMARY KEY (ID)
);

-- TABLE: CONTACTS
CREATE TABLE CONTACTS (
    ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT CONTACTS_PK PRIMARY KEY (ID)
);

-- TABLE: CUSTOMERS
CREATE TABLE CUSTOMERS (
    ID INT  NOT NULL,
    NAME VARCHAR(150)  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID)
);

-- TABLE: CUSTOMERS_CONTACTS
CREATE TABLE CUSTOMERS_CONTACTS (
    ID INT  NOT NULL,
    CUSTOMERS_ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT CUSTOMERS_CONTACTS_PK PRIMARY KEY (ID)
);

-- TABLE: DEMOGRAHPICS
CREATE TABLE DEMOGRAHPICS (
    ID INT  NOT NULL,
    LONG DECIMAL(12,8)  NOT NULL,
    LAT DECIMAL(12,8)  NOT NULL,
    DESCRIPTION VARCHAR(150)  NULL,
    CONTACTS_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT DEMOGRAHPICS_PK PRIMARY KEY (ID)
);

-- TABLE: EMAILS
CREATE TABLE EMAILS (
    ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    ADDRESS VARCHAR(100)  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT EMAILS_PK PRIMARY KEY (ID)
);

-- TABLE: EMPLOYEES
CREATE TABLE EMPLOYEES (
    ID INT  NOT NULL,
    EMPLOYEES_ID INT  NULL,
    HIRE_DATE DATE  NOT NULL,
    RESIGNATION_DATE DATE  NOT NULL,
    CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID)
);

-- TABLE: EMPLOYEES_CONTACTS
CREATE TABLE EMPLOYEES_CONTACTS (
    ID INT  NOT NULL,
    EMPLOYEES_ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT EMPLOYEES_CONTACTS_PK PRIMARY KEY (ID)
);

-- TABLE: EMPLOYEES_DETAILS
CREATE TABLE EMPLOYEES_DETAILS (
    ID INT  NOT NULL,
    FIRST_NAME VARCHAR(150)  NOT NULL,
    LAST_NAME VARCHAR(150)  NULL,
    TITLE VARCHAR(100)  NULL,
    TITLE_OF_COURTESY VARCHAR(100)  NULL,
    BRITH_DATE INT  NOT NULL,
    EMPLOYEES_ID INT  NOT NULL,
    NOTES TEXT  NULL,
    CONSTRAINT EMPLOYEES_DETAILS_PK PRIMARY KEY (ID)
);

-- TABLE: ORDERS
CREATE TABLE ORDERS (
    ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT ORDERS_PK PRIMARY KEY (ID)
);

-- TABLE: ORDERS_CONTACTS
CREATE TABLE ORDERS_CONTACTS (
    ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    ORDERS_ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    CONSTRAINT ORDERS_CONTACTS_PK PRIMARY KEY (ID)
);

-- TABLE: ORDERS_CUSTOMERS
CREATE TABLE ORDERS_CUSTOMERS (
    ID INT  NOT NULL,
    CUSTOMERS_ID INT  NOT NULL,
    ORDERS_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT ORDERS_CUSTOMERS_PK PRIMARY KEY (ID)
);

-- TABLE: ORDERS_DETAILS
CREATE TABLE ORDERS_DETAILS (
    ID INT  NOT NULL,
    UNIT_PRICE DECIMAL(12,2)  NOT NULL,
    QUANTITY INT  NOT NULL,
    DISCOUNT DECIMAL(12,2)  NOT NULL,
    ORDERS_ID INT  NOT NULL,
    PRODUCTS_ID INT  NOT NULL,
    CONSTRAINT ORDERS_DETAILS_PK PRIMARY KEY (ID)
);

-- TABLE: ORDERS_EMPLOYEES
CREATE TABLE ORDERS_EMPLOYEES (
    ID INT  NOT NULL,
    ORDERS_ID INT  NOT NULL,
    EMPLOYEES_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT ORDERS_EMPLOYEES_PK PRIMARY KEY (ID)
);

-- TABLE: ORDERS_SHIPPERS
CREATE TABLE ORDERS_SHIPPERS (
    ID INT  NOT NULL,
    SHIPPERS_ID INT  NOT NULL,
    ORDERS_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT ORDERS_SHIPPERS_PK PRIMARY KEY (ID)
);

-- TABLE: PHONES
CREATE TABLE PHONES (
    ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    NUMBER VARCHAR(20)  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSER_REGISTER DATE  NULL,
    CONSTRAINT PHONES_PK PRIMARY KEY (ID)
);

-- TABLE: PICTURES
CREATE TABLE PICTURES (
    ID INT  NOT NULL,
    PATH TEXT  NOT NULL,
    CONSTRAINT PICTURES_PK PRIMARY KEY (ID)
);

-- TABLE: PICTURES_CATEGORIES
CREATE TABLE PICTURES_CATEGORIES (
    ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CATEGORIES_ID INT  NOT NULL,
    PICTURES_ID INT  NOT NULL,
    CONSTRAINT PICTURES_CATEGORIES_PK PRIMARY KEY (ID)
);

-- TABLE: PICTURES_EMPLOYEES
CREATE TABLE PICTURES_EMPLOYEES (
    ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NOT NULL,
    PICTURES_ID INT  NOT NULL,
    EMPLOYEES_ID INT  NOT NULL,
    CONSTRAINT PICTURES_EMPLOYEES_PK PRIMARY KEY (ID)
);

-- TABLE: PICTURES_PRODUCTS
CREATE TABLE PICTURES_PRODUCTS (
    ID INT  NOT NULL,
    PRODUCTS_ID INT  NOT NULL,
    PICTURES_ID INT  NOT NULL,
    DATE_REGSITER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT PICTURES_PRODUCTS_PK PRIMARY KEY (ID)
);

-- TABLE: PRODUCTS
CREATE TABLE PRODUCTS (
    ID INT  NOT NULL,
    CATEGORIES_ID INT  NOT NULL,
    SUPPLIERS_ID INT  NOT NULL,
    NAME VARCHAR(150)  NOT NULL,
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (ID)
);

-- TABLE: SHIPPERS
CREATE TABLE SHIPPERS (
    ID INT  NOT NULL,
    NAME VARCHAR(150)  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT SHIPPERS_PK PRIMARY KEY (ID)
);

-- TABLE: SHIPPERS_CONTACTS
CREATE TABLE SHIPPERS_CONTACTS (
    ID INT  NOT NULL,
    SHIPPERS_ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT SHIPPERS_CONTACTS_PK PRIMARY KEY (ID)
);

-- TABLE: STOCK
CREATE TABLE STOCK (
    ID INT  NOT NULL,
    QUANTITY INT  NOT NULL,
    QUANTITY_PER_UNIT INT  NOT NULL,
    REORDER_LEVEL SMALLINT  NOT NULL,
    STOCK_ADDRESS VARCHAR(150)  NOT NULL,
    CONSTRAINT STOCK_PK PRIMARY KEY (ID)
);

-- TABLE: STOCK_DETAILS
CREATE TABLE STOCK_DETAILS (
    ID INT  NOT NULL,
    PRODUCTS_ID INT  NOT NULL,
    STOCK_ID INT  NOT NULL,
    UNIT_PRICE DECIMAL(12,2)  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT STOCK_DETAILS_PK PRIMARY KEY (ID)
);

-- TABLE: SUPPLIERS
CREATE TABLE SUPPLIERS (
    ID INT  NOT NULL,
    NAME VARCHAR(150)  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT SUPPLIERS_PK PRIMARY KEY (ID)
);

-- TABLE: SUPPLIERS_CONTACTS
CREATE TABLE SUPPLIERS_CONTACTS (
    ID INT  NOT NULL,
    SUPPLIERS_ID INT  NOT NULL,
    CONTACTS_ID INT  NOT NULL,
    DATE_REGISTER DATE  NOT NULL,
    CLOSE_REGISTER DATE  NULL,
    CONSTRAINT SUPPLIERS_CONTACTS_PK PRIMARY KEY (ID)
);

-- FOREIGN KEYS
-- REFERENCE: ADDRESSES_CONTACTS (TABLE: ADDRESSES)
ALTER TABLE ADDRESSES ADD CONSTRAINT ADDRESSES_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: CUSTOMERS_CONTACTS_CONTACTS (TABLE: CUSTOMERS_CONTACTS)
ALTER TABLE CUSTOMERS_CONTACTS ADD CONSTRAINT CUSTOMERS_CONTACTS_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: CUSTOMERS_CONTACTS_CUSTOMERS (TABLE: CUSTOMERS_CONTACTS)
ALTER TABLE CUSTOMERS_CONTACTS ADD CONSTRAINT CUSTOMERS_CONTACTS_CUSTOMERS
    FOREIGN KEY (CUSTOMERS_ID)
    REFERENCES CUSTOMERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: DEMOGRAHPICS_CONTACTS (TABLE: DEMOGRAHPICS)
ALTER TABLE DEMOGRAHPICS ADD CONSTRAINT DEMOGRAHPICS_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: EMAILS_CONTACTS (TABLE: EMAILS)
ALTER TABLE EMAILS ADD CONSTRAINT EMAILS_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: EMPLOYEES_CONTACTS_CONTACTS (TABLE: EMPLOYEES_CONTACTS)
ALTER TABLE EMPLOYEES_CONTACTS ADD CONSTRAINT EMPLOYEES_CONTACTS_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: EMPLOYEES_CONTACTS_EMPLOYEES (TABLE: EMPLOYEES_CONTACTS)
ALTER TABLE EMPLOYEES_CONTACTS ADD CONSTRAINT EMPLOYEES_CONTACTS_EMPLOYEES
    FOREIGN KEY (EMPLOYEES_ID)
    REFERENCES EMPLOYEES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: EMPLOYEES_DETAILS_EMPLOYEES (TABLE: EMPLOYEES_DETAILS)
ALTER TABLE EMPLOYEES_DETAILS ADD CONSTRAINT EMPLOYEES_DETAILS_EMPLOYEES
    FOREIGN KEY (EMPLOYEES_ID)
    REFERENCES EMPLOYEES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: EMPLOYEES_EMPLOYEES (TABLE: EMPLOYEES)
ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPLOYEES_EMPLOYEES
    FOREIGN KEY (EMPLOYEES_ID)
    REFERENCES EMPLOYEES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_CONTACTS_CONTACTS (TABLE: ORDERS_CONTACTS)
ALTER TABLE ORDERS_CONTACTS ADD CONSTRAINT ORDERS_CONTACTS_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_CONTACTS_ORDERS (TABLE: ORDERS_CONTACTS)
ALTER TABLE ORDERS_CONTACTS ADD CONSTRAINT ORDERS_CONTACTS_ORDERS
    FOREIGN KEY (ORDERS_ID)
    REFERENCES ORDERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_CUSTOMERS_CUSTOMERS (TABLE: ORDERS_CUSTOMERS)
ALTER TABLE ORDERS_CUSTOMERS ADD CONSTRAINT ORDERS_CUSTOMERS_CUSTOMERS
    FOREIGN KEY (CUSTOMERS_ID)
    REFERENCES CUSTOMERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_CUSTOMERS_ORDERS (TABLE: ORDERS_CUSTOMERS)
ALTER TABLE ORDERS_CUSTOMERS ADD CONSTRAINT ORDERS_CUSTOMERS_ORDERS
    FOREIGN KEY (ORDERS_ID)
    REFERENCES ORDERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_DETAILS_ORDERS (TABLE: ORDERS_DETAILS)
ALTER TABLE ORDERS_DETAILS ADD CONSTRAINT ORDERS_DETAILS_ORDERS
    FOREIGN KEY (ORDERS_ID)
    REFERENCES ORDERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_DETAILS_PRODUCTS (TABLE: ORDERS_DETAILS)
ALTER TABLE ORDERS_DETAILS ADD CONSTRAINT ORDERS_DETAILS_PRODUCTS
    FOREIGN KEY (PRODUCTS_ID)
    REFERENCES PRODUCTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_EMPLOYEES_EMPLOYEES (TABLE: ORDERS_EMPLOYEES)
ALTER TABLE ORDERS_EMPLOYEES ADD CONSTRAINT ORDERS_EMPLOYEES_EMPLOYEES
    FOREIGN KEY (EMPLOYEES_ID)
    REFERENCES EMPLOYEES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_EMPLOYEES_ORDERS (TABLE: ORDERS_EMPLOYEES)
ALTER TABLE ORDERS_EMPLOYEES ADD CONSTRAINT ORDERS_EMPLOYEES_ORDERS
    FOREIGN KEY (ORDERS_ID)
    REFERENCES ORDERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_SHIPPERS_ORDERS (TABLE: ORDERS_SHIPPERS)
ALTER TABLE ORDERS_SHIPPERS ADD CONSTRAINT ORDERS_SHIPPERS_ORDERS
    FOREIGN KEY (ORDERS_ID)
    REFERENCES ORDERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: ORDERS_SHIPPERS_SHIPPERS (TABLE: ORDERS_SHIPPERS)
ALTER TABLE ORDERS_SHIPPERS ADD CONSTRAINT ORDERS_SHIPPERS_SHIPPERS
    FOREIGN KEY (SHIPPERS_ID)
    REFERENCES SHIPPERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PHONES_CONTACTS (TABLE: PHONES)
ALTER TABLE PHONES ADD CONSTRAINT PHONES_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PICTURES_CATEGORIES_CATEGORIES (TABLE: PICTURES_CATEGORIES)
ALTER TABLE PICTURES_CATEGORIES ADD CONSTRAINT PICTURES_CATEGORIES_CATEGORIES
    FOREIGN KEY (CATEGORIES_ID)
    REFERENCES CATEGORIES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PICTURES_CATEGORIES_PICTURES (TABLE: PICTURES_CATEGORIES)
ALTER TABLE PICTURES_CATEGORIES ADD CONSTRAINT PICTURES_CATEGORIES_PICTURES
    FOREIGN KEY (PICTURES_ID)
    REFERENCES PICTURES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PICTURES_EMPLOYEES_EMPLOYEES (TABLE: PICTURES_EMPLOYEES)
ALTER TABLE PICTURES_EMPLOYEES ADD CONSTRAINT PICTURES_EMPLOYEES_EMPLOYEES
    FOREIGN KEY (EMPLOYEES_ID)
    REFERENCES EMPLOYEES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PICTURES_EMPLOYEES_PICTURES (TABLE: PICTURES_EMPLOYEES)
ALTER TABLE PICTURES_EMPLOYEES ADD CONSTRAINT PICTURES_EMPLOYEES_PICTURES
    FOREIGN KEY (PICTURES_ID)
    REFERENCES PICTURES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PICTURES_PRODUCTS_PICTURES (TABLE: PICTURES_PRODUCTS)
ALTER TABLE PICTURES_PRODUCTS ADD CONSTRAINT PICTURES_PRODUCTS_PICTURES
    FOREIGN KEY (PICTURES_ID)
    REFERENCES PICTURES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PICTURES_PRODUCTS_PRODUCTS (TABLE: PICTURES_PRODUCTS)
ALTER TABLE PICTURES_PRODUCTS ADD CONSTRAINT PICTURES_PRODUCTS_PRODUCTS
    FOREIGN KEY (PRODUCTS_ID)
    REFERENCES PRODUCTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PRODUCTS_CATEGORIES (TABLE: PRODUCTS)
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_CATEGORIES
    FOREIGN KEY (CATEGORIES_ID)
    REFERENCES CATEGORIES (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: PRODUCTS_SUPPLIERS (TABLE: PRODUCTS)
ALTER TABLE PRODUCTS ADD CONSTRAINT PRODUCTS_SUPPLIERS
    FOREIGN KEY (SUPPLIERS_ID)
    REFERENCES SUPPLIERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: SHIPPERS_CONTACTS_CONTACTS (TABLE: SHIPPERS_CONTACTS)
ALTER TABLE SHIPPERS_CONTACTS ADD CONSTRAINT SHIPPERS_CONTACTS_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: SHIPPERS_CONTACTS_SHIPPERS (TABLE: SHIPPERS_CONTACTS)
ALTER TABLE SHIPPERS_CONTACTS ADD CONSTRAINT SHIPPERS_CONTACTS_SHIPPERS
    FOREIGN KEY (SHIPPERS_ID)
    REFERENCES SHIPPERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: STOCK_DETAILS_PRODUCTS (TABLE: STOCK_DETAILS)
ALTER TABLE STOCK_DETAILS ADD CONSTRAINT STOCK_DETAILS_PRODUCTS
    FOREIGN KEY (PRODUCTS_ID)
    REFERENCES PRODUCTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: STOCK_DETAILS_STOCK (TABLE: STOCK_DETAILS)
ALTER TABLE STOCK_DETAILS ADD CONSTRAINT STOCK_DETAILS_STOCK
    FOREIGN KEY (STOCK_ID)
    REFERENCES STOCK (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: SUPPLIERS_CONTACTS_CONTACTS (TABLE: SUPPLIERS_CONTACTS)
ALTER TABLE SUPPLIERS_CONTACTS ADD CONSTRAINT SUPPLIERS_CONTACTS_CONTACTS
    FOREIGN KEY (CONTACTS_ID)
    REFERENCES CONTACTS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- REFERENCE: SUPPLIERS_CONTACTS_SUPPLIERS (TABLE: SUPPLIERS_CONTACTS)
ALTER TABLE SUPPLIERS_CONTACTS ADD CONSTRAINT SUPPLIERS_CONTACTS_SUPPLIERS
    FOREIGN KEY (SUPPLIERS_ID)
    REFERENCES SUPPLIERS (ID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- END OF FILE.


