-- CREATED BY VERTABELO (HTTP://VERTABELO.COM)
-- LAST MODIFICATION DATE: 2024-04-04 21:51:17.94

-- FOREIGN KEYS
ALTER TABLE ADDRESSES
    DROP CONSTRAINT ADDRESSES_CONTACTS;

ALTER TABLE CUSTOMERS_CONTACTS
    DROP CONSTRAINT CUSTOMERS_CONTACTS_CONTACTS;

ALTER TABLE CUSTOMERS_CONTACTS
    DROP CONSTRAINT CUSTOMERS_CONTACTS_CUSTOMERS;

ALTER TABLE DEMOGRAHPICS
    DROP CONSTRAINT DEMOGRAHPICS_CONTACTS;

ALTER TABLE EMAILS
    DROP CONSTRAINT EMAILS_CONTACTS;

ALTER TABLE EMPLOYEES_CONTACTS
    DROP CONSTRAINT EMPLOYEES_CONTACTS_CONTACTS;

ALTER TABLE EMPLOYEES_CONTACTS
    DROP CONSTRAINT EMPLOYEES_CONTACTS_EMPLOYEES;

ALTER TABLE EMPLOYEES_DETAILS
    DROP CONSTRAINT EMPLOYEES_DETAILS_EMPLOYEES;

ALTER TABLE EMPLOYEES
    DROP CONSTRAINT EMPLOYEES_EMPLOYEES;

ALTER TABLE ORDERS_CONTACTS
    DROP CONSTRAINT ORDERS_CONTACTS_CONTACTS;

ALTER TABLE ORDERS_CONTACTS
    DROP CONSTRAINT ORDERS_CONTACTS_ORDERS;

ALTER TABLE ORDERS_CUSTOMERS
    DROP CONSTRAINT ORDERS_CUSTOMERS_CUSTOMERS;

ALTER TABLE ORDERS_CUSTOMERS
    DROP CONSTRAINT ORDERS_CUSTOMERS_ORDERS;

ALTER TABLE ORDERS_DETAILS
    DROP CONSTRAINT ORDERS_DETAILS_ORDERS;

ALTER TABLE ORDERS_DETAILS
    DROP CONSTRAINT ORDERS_DETAILS_PRODUCTS;

ALTER TABLE ORDERS_EMPLOYEES
    DROP CONSTRAINT ORDERS_EMPLOYEES_EMPLOYEES;

ALTER TABLE ORDERS_EMPLOYEES
    DROP CONSTRAINT ORDERS_EMPLOYEES_ORDERS;

ALTER TABLE ORDERS_SHIPPERS
    DROP CONSTRAINT ORDERS_SHIPPERS_ORDERS;

ALTER TABLE ORDERS_SHIPPERS
    DROP CONSTRAINT ORDERS_SHIPPERS_SHIPPERS;

ALTER TABLE PHONES
    DROP CONSTRAINT PHONES_CONTACTS;

ALTER TABLE PICTURES_CATEGORIES
    DROP CONSTRAINT PICTURES_CATEGORIES_CATEGORIES;

ALTER TABLE PICTURES_CATEGORIES
    DROP CONSTRAINT PICTURES_CATEGORIES_PICTURES;

ALTER TABLE PICTURES_EMPLOYEES
    DROP CONSTRAINT PICTURES_EMPLOYEES_EMPLOYEES;

ALTER TABLE PICTURES_EMPLOYEES
    DROP CONSTRAINT PICTURES_EMPLOYEES_PICTURES;

ALTER TABLE PICTURES_PRODUCTS
    DROP CONSTRAINT PICTURES_PRODUCTS_PICTURES;

ALTER TABLE PICTURES_PRODUCTS
    DROP CONSTRAINT PICTURES_PRODUCTS_PRODUCTS;

ALTER TABLE PRODUCTS
    DROP CONSTRAINT PRODUCTS_CATEGORIES;

ALTER TABLE PRODUCTS
    DROP CONSTRAINT PRODUCTS_SUPPLIERS;

ALTER TABLE SHIPPERS_CONTACTS
    DROP CONSTRAINT SHIPPERS_CONTACTS_CONTACTS;

ALTER TABLE SHIPPERS_CONTACTS
    DROP CONSTRAINT SHIPPERS_CONTACTS_SHIPPERS;

ALTER TABLE STOCK_DETAILS
    DROP CONSTRAINT STOCK_DETAILS_PRODUCTS;

ALTER TABLE STOCK_DETAILS
    DROP CONSTRAINT STOCK_DETAILS_STOCK;

ALTER TABLE SUPPLIERS_CONTACTS
    DROP CONSTRAINT SUPPLIERS_CONTACTS_CONTACTS;

ALTER TABLE SUPPLIERS_CONTACTS
    DROP CONSTRAINT SUPPLIERS_CONTACTS_SUPPLIERS;

-- TABLES
DROP TABLE ADDRESSES;

DROP TABLE CATEGORIES;

DROP TABLE CONTACTS;

DROP TABLE CUSTOMERS;

DROP TABLE CUSTOMERS_CONTACTS;

DROP TABLE DEMOGRAHPICS;

DROP TABLE EMAILS;

DROP TABLE EMPLOYEES;

DROP TABLE EMPLOYEES_CONTACTS;

DROP TABLE EMPLOYEES_DETAILS;

DROP TABLE ORDERS;

DROP TABLE ORDERS_CONTACTS;

DROP TABLE ORDERS_CUSTOMERS;

DROP TABLE ORDERS_DETAILS;

DROP TABLE ORDERS_EMPLOYEES;

DROP TABLE ORDERS_SHIPPERS;

DROP TABLE PHONES;

DROP TABLE PICTURES;

DROP TABLE PICTURES_CATEGORIES;

DROP TABLE PICTURES_EMPLOYEES;

DROP TABLE PICTURES_PRODUCTS;

DROP TABLE PRODUCTS;

DROP TABLE SHIPPERS;

DROP TABLE SHIPPERS_CONTACTS;

DROP TABLE STOCK;

DROP TABLE STOCK_DETAILS;

DROP TABLE SUPPLIERS;

DROP TABLE SUPPLIERS_CONTACTS;

-- END OF FILE.


